### ISSUE TITLE
Problem with training

### ISSUE THREAD

**Issue by LucyFann** [emorynlp/levi-graph-amr-parser#2]
Hi, I follow your steps to precess data(the dataset is amr3.0), but got RuntimeError while training. Here is my Error message:
`levi_graph = True
('tok', 975, 0.804928522804629)
('lem', 954, 0.8633356024506467)
('pos', 45, 0.9997277059223962)
('ner', 29, 0.9997277059223962)
('predictable_concept', 452, 0.9402519807767242)
('concept', 986, 0.9146389288315375)
('rel', 4, 1.0)
('word_char', 60, 0.9954075010815667)
('concept_char', 56, 0.9993265489374439)
read from data/AMR/amr_3.0/dev.txt.features.preproc, 1722 amrs
read from data/AMR/amr_3.0/train.txt.features.preproc, 1898 amrs
Model will be saved in levi_model
./amr_parser/transformer.py:134: UserWarning: Output 0 of SplitBackward is a view and is being modified inplace. This view is an output of a function that returns multiple views. Inplace operators on such views are being deprecated and will be forbidden starting from version 1.8. Consider using `unsafe_` version of the function that produced this view or don't modify this view inplace. (Triggered internally at  /pytorch/torch/csrc/autograd/variable.cpp:491.)
  q *= self.scaling
Traceback (most recent call last):
  File "amr_parser/train.py", line 303, in <module>
    main(0, args)
  File "amr_parser/train.py", line 257, in main
    loss.backward()
  File "/home/fansq2/miniconda3/envs/levi/lib/python3.6/site-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/fansq2/miniconda3/envs/levi/lib/python3.6/site-packages/torch/autograd/__init__.py", line 132, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [52, 218, 1536]], which is output 0 of AddBackward0, is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).`

This is the code of the error part in amr_parser/transformer.py(the same with the repository)
`q *= self.scaling
q = q.contiguous().view(tgt_len, bsz * self.num_heads, self.head_dim).transpose(0, 1)
k = k.contiguous().view(-1, bsz * self.num_heads, self.head_dim).transpose(0, 1)
v = v.contiguous().view(-1, bsz * self.num_heads, self.head_dim).transpose(0, 1)
src_len = k.size(1)`
Can you please advise how to fix that? Thank you.

**Comment by hankcs** [comment]
Thank you for reporting this bug. We might have uploaded a fossil version. Please do a `git pull` to get the patch.
