### ISSUE TITLE
How to generate the amr_3.0_utils.tgz in download_artifacts.sh

### ISSUE THREAD

**Issue by lizhzh8** [emorynlp/levi-graph-amr-parser#6]
Hi han,
first of all, thanks for your work.
I wonder about how to generate amr_3.0_utils.tgz  in download_artifacts.sh. 
In https://od.hankcs.com/research/amr2020/,there are amr_2.0_utils.tgz and amr_3.0_utils.tgz,but I don't know how to generate these compressed packages.
Thanks a lot!

**Comment by hankcs** [comment]
Hi, it has been a while and I cannot recall all the details. I remember that I copied most materials from the public amr_2.0_utils and update them with new amr 3.0 contents. Some of them are frequency counters which are easy to update, spotlight_wiki.json was predicted using the latest spotlight model.

**Comment by lizhzh8** [comment]
> Hi, it has been a while and I cannot recall all the details. I remember that I copied most materials from the public amr_2.0_utils and update them with new amr 3.0 contents. Some of them are frequency counters which are easy to update, spotlight_wiki.json was predicted using the latest spotlight model.

Firstly,thank you for your patience.Amr_2.0_utils and amr_3.0_utils is indeed similarly. Actually I want to test the result using Chinese stype amr data (camr).So my question is that: are there any methods or knowledge to generate those utils json using  Chinese stype amr data (camr2.0) except frequence counters part.
I appreciate your reply，thank you .

**Comment by hankcs** [comment]
Good question, actually I once tried to generate Chinese utils but eventually gave up because it's not enough to just count the frequencies and hope they will work, since the recategorization is language specific and hard coded. Same stories for the polarity related codes too.
